name: Check PR & Deploy Preview
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  checks-preview-pr:
    name: Check & Deploy Preview
    runs-on: ubuntu-latest
    
    permissions: 
      contents: read
      packages: write
      pull-requests: write 

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: pnpm install
      - run: pnpm lint
      - run: npm install --global vercel
      - run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - id: preview-deploy
        run: |
          URL=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})
          echo "URL=$URL" >> "$GITHUB_OUTPUT"
      - uses: thollander/actions-comment-pull-request@v2.4.3
        with: 
          message: |
            Preview URL: ${{ steps.preview-deploy.outputs.URL }}
          comment_tag: preview-info